{"name": "Проверка авторизации под не существующим пользователем", "status": "passed", "steps": [{"name": "Логин с не верным логином и паролем", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': '17', 'password': '17'}"}], "start": 1748871290467, "stop": 1748871290595}], "parameters": [{"name": "payload", "value": "{'email': '17', 'password': '17'}"}], "start": 1748871290467, "stop": 1748871290596, "uuid": "a14e7363-bd37-4590-94f7-b458ab877eba", "historyId": "fdc9648cf8fd60e5e9c4b2fbdb03a02b", "testCaseId": "1c69549ff653edcbffbd94daafbebf66", "fullName": "test.user.test_users.TestUsers#test_auth_user_fail", "labels": [{"name": "parentSuite", "value": "test.user"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-7J4I0FQ"}, {"name": "thread", "value": "19016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.user.test_users"}]}